export const escapeHtml = (value = "") => String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" })[character]);

const formatDate = (value, locale) => new Intl.DateTimeFormat(locale === "cs" ? "cs-CZ" : "en-GB", { dateStyle: "long", timeZone: "Europe/Prague" }).format(new Date(value));

const topicLabel = (topic, lang) => ({
  ai: lang === "cs" ? "Umělá inteligence" : "Artificial intelligence",
  security: lang === "cs" ? "Bezpečnost" : "Security",
  software: lang === "cs" ? "Software" : "Software",
  internet: lang === "cs" ? "Internet" : "Internet",
  business: lang === "cs" ? "Digitální ekonomika" : "Digital economy",
  science: lang === "cs" ? "Věda" : "Science"
})[topic] ?? topic;

function layout({ lang, title, description, path, body, articleData = null }) {
  const cs = lang === "cs";
  const alternate = cs ? `/en${path}` : path.replace(/^\/en/, "") || "/blog/";
  const canonical = `https://vcode.zeleznalady.cz${path}`;
  const schema = JSON.stringify(articleData ?? { "@context": "https://schema.org", "@type": "Blog", name: "VCode Blog", url: canonical, inLanguage: lang, publisher: { "@type": "Organization", name: "VCode", url: "https://vcode.zeleznalady.cz/" } }).replaceAll("<", "\\u003c");
  return `<!doctype html><html lang="${lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#071525"><meta name="description" content="${escapeHtml(description)}"><meta name="author" content="VCode"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="cs" href="https://vcode.zeleznalady.cz${cs ? path : alternate}"><link rel="alternate" hreflang="en" href="https://vcode.zeleznalady.cz${cs ? alternate : path}"><link rel="alternate" type="application/rss+xml" title="VCode blog" href="${cs ? "/blog/feed.xml" : "/en/blog/feed.xml"}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta property="og:type" content="${articleData ? "article" : "website"}"><meta property="og:site_name" content="VCode"><meta property="og:title" content="${escapeHtml(title)}"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="https://vcode.zeleznalady.cz/vcode-social.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escapeHtml(title)}"><meta name="twitter:description" content="${escapeHtml(description)}"><meta name="twitter:image" content="https://vcode.zeleznalady.cz/vcode-social.png"><script type="application/ld+json">${schema}</script><link rel="stylesheet" href="/blog-assets/blog.css"><title>${escapeHtml(title)}</title></head><body><a class="skip-link" href="#content">${cs ? "Přeskočit na obsah" : "Skip to content"}</a><div class="shell"><header class="site-header"><a class="brand" href="${cs ? "/" : "/en/"}"><img class="mark" src="/favicon.svg" width="34" height="34" alt="">VCode</a><nav id="site-navigation" aria-label="${cs ? "Hlavní navigace" : "Main navigation"}"><a href="${cs ? "/#aplikace" : "/en/#apps"}">${cs ? "Aplikace" : "Apps"}</a><a aria-current="page" href="${cs ? "/blog/" : "/en/blog/"}">Blog</a><a href="${cs ? "/navody/" : "/en/guides/"}">${cs ? "Návody" : "Guides"}</a><a href="${cs ? "/podpora/" : "/en/support/"}">${cs ? "Podpora" : "Support"}</a></nav><div class="header-actions"><a class="language" href="${alternate}" hreflang="${cs ? "en" : "cs"}">${cs ? "EN" : "CS"}</a><button class="menu-toggle" type="button" aria-controls="site-navigation" aria-expanded="false" aria-label="${cs ? "Otevřít nabídku" : "Open menu"}"><span></span><span></span></button></div></header><main id="content">${body}</main><footer class="site-footer"><div><strong>VCode</strong><p>${cs ? "Technologie, na které je spoleh." : "Technology you can rely on."}</p></div><div class="footer-links"><a href="${cs ? "/blog/" : "/en/blog/"}">Blog</a><a href="${cs ? "/navody/" : "/en/guides/"}">${cs ? "Návody" : "Guides"}</a><a href="${cs ? "/podpora/" : "/en/support/"}">${cs ? "Podpora" : "Support"}</a></div><small>© ${new Date().getFullYear()} VCode</small></footer></div><script type="module" src="/site.js"></script></body></html>`;
}

export function renderIndex(articles, lang) {
  const cs = lang === "cs";
  const prefix = cs ? "/blog" : "/en/blog";
  const cards = articles.length ? articles.map((article) => `<a class="article-card" href="${prefix}/${encodeURIComponent(article.slug)}/"><time datetime="${new Date(article.published_at).toISOString()}">${formatDate(article.published_at, lang)}</time><div><h2>${escapeHtml(article.title)}</h2><p>${escapeHtml(article.dek)}</p></div><span class="arrow" aria-hidden="true">↗</span></a>`).join("") : `<div class="empty">${cs ? "První technologický přehled právě připravujeme." : "We are preparing the first technology briefing."}</div>`;
  return layout({ lang, title: cs ? "Technologický blog — VCode" : "Technology blog — VCode", description: cs ? "Věcný přehled důležitých novinek z technologií a umělé inteligence s odkazy na původní zdroje." : "A clear briefing on technology and AI developments, with links to original sources.", path: `${prefix}/`, body: `<section class="blog-hero"><p class="kicker">VCode / ${cs ? "Technologický přehled" : "Technology briefing"}</p><h1>${cs ? "Co se mění.<br>Co z toho plyne." : "What changed.<br>Why it matters."}</h1><p>${cs ? "Pravidelně vybíráme podstatné technologické novinky, ověřujeme jejich původ a dáváme je do srozumitelného kontextu." : "We regularly select meaningful technology news, verify its provenance and put it into clear context."}</p></section><section class="article-list" aria-label="${cs ? "Články" : "Articles"}">${cards}</section>` });
}

export function renderArticle(article, comments, lang, notice) {
  const cs = lang === "cs";
  const prefix = cs ? "/blog" : "/en/blog";
  const sourceById = new Map(article.sources.map((source) => [source.id, source]));
  const sections = article.sections.map((section) => {
    const citations = section.source_ids.map((id) => sourceById.get(id)).filter(Boolean).map((source) => `<a href="${escapeHtml(source.url)}" rel="noopener noreferrer">${escapeHtml(source.sourceName)} ↗</a>`).join("");
    return `<section><h2>${escapeHtml(section.heading)}</h2>${section.paragraphs.map((paragraph) => `<p>${escapeHtml(paragraph)}</p>`).join("")}<div class="section-sources" aria-label="${cs ? "Zdroje této části" : "Sources for this section"}">${citations}</div></section>`;
  }).join("");
  const points = article.key_points.map((point) => `<li>${escapeHtml(point)}</li>`).join("");
  const sources = article.sources.map((source) => `<a href="${escapeHtml(source.url)}" rel="noopener noreferrer"><strong>${escapeHtml(source.title)}</strong><span>${escapeHtml(source.sourceName)}${source.publishedAt ? ` · ${formatDate(source.publishedAt, lang)}` : ""} ↗</span></a>`).join("");
  const commentRows = comments.length ? comments.map((comment) => `<article class="comment"><header><strong>${escapeHtml(comment.display_name)}</strong><time datetime="${new Date(comment.created_at).toISOString()}">${formatDate(comment.created_at, lang)}</time></header><p>${escapeHtml(comment.body)}</p></article>`).join("") : `<p>${cs ? "Zatím bez komentářů." : "No comments yet."}</p>`;
  const noticeHtml = notice ? `<p class="notice" role="status">${cs ? "Děkujeme. Komentář jsme přijali ke kontrole." : "Thank you. Your comment has been received for review."}</p>` : "";
  const disclosure = cs
    ? "Článek připravila automatizovaná redakce VCode z uvedených zdrojů. Před publikací prošel strukturální a bezpečnostní kontrolou."
    : "This article was prepared by VCode's automated newsroom from the listed sources. It passed structural and safety checks before publication.";
  return layout({ lang, title: `${article.title} — VCode`, description: article.dek, path: `${prefix}/${article.slug}/`, articleData: { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.dek, datePublished: new Date(article.published_at).toISOString(), inLanguage: lang, mainEntityOfPage: `https://vcode.zeleznalady.cz${prefix}/${article.slug}/`, author: { "@type": "Organization", name: "VCode" }, publisher: { "@type": "Organization", name: "VCode", url: "https://vcode.zeleznalady.cz/" }, image: "https://vcode.zeleznalady.cz/vcode-social.png" }, body: `<article><header class="article-header"><a class="kicker" href="${prefix}/">← ${cs ? "Technologický blog" : "Technology blog"}</a><h1>${escapeHtml(article.title)}</h1><p class="article-dek">${escapeHtml(article.dek)}</p><div class="meta"><time datetime="${new Date(article.published_at).toISOString()}">${formatDate(article.published_at, lang)}</time><span>${escapeHtml(topicLabel(article.topic, lang))}</span><span>${cs ? "Zdroje jsou uvedeny pod článkem" : "Sources are listed below"}</span></div></header><div class="hero-art"><img src="/blog-assets/${encodeURIComponent(article.slug)}.svg" alt="" width="1400" height="600"></div><div class="article-grid"><div class="article-body">${sections}</div><aside class="points"><h2>${cs ? "V kostce" : "Key points"}</h2><ul>${points}</ul></aside></div><section class="sources"><h2>${cs ? "Původní zdroje" : "Original sources"}</h2><p class="form-note">${escapeHtml(disclosure)}</p><div class="source-list">${sources}</div></section></article><section class="comments"><h2>${cs ? "Komentáře" : "Comments"}</h2>${noticeHtml}${commentRows}<form class="comment-form" method="post" action="/api/blog/${encodeURIComponent(article.slug)}/comments"><input type="hidden" name="lang" value="${lang}"><label>${cs ? "Jméno" : "Name"}<input name="name" autocomplete="name" minlength="2" maxlength="60" required></label><label>${cs ? "E-mail (nezveřejníme)" : "Email (not published)"}<input name="email" type="email" autocomplete="email" maxlength="160"></label><label class="full">${cs ? "Komentář" : "Comment"}<textarea name="body" minlength="10" maxlength="2000" required></textarea></label><label class="honeypot" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><p class="form-note">${cs ? "Komentáře procházejí automatickou a případně ruční kontrolou. Podrobnosti najdete v zásadách soukromí." : "Comments undergo automated and, when needed, manual review. See our privacy notice for details."} <a href="${cs ? "/soukromi/" : "/en/privacy/"}">${cs ? "Soukromí →" : "Privacy →"}</a></p><button type="submit">${cs ? "Odeslat komentář" : "Submit comment"}</button></form></section>` });
}

export function renderHeroSvg(variant) {
  const patterns = { signals: "M90 420C250 170 430 500 610 250S980 120 1310 330", grid: "M0 100H1400M0 220H1400M0 340H1400M0 460H1400M180 0V600M420 0V600M660 0V600M900 0V600M1140 0V600", orbit: "M240 300a460 220 0 1 0 920 0 460 220 0 1 0-920 0", layers: "M120 410L700 110l580 300-580 120zM230 450l470 90 470-90", network: "M100 430L360 170l310 210 280-250 350 300" };
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1400 600" role="img"><defs><linearGradient id="b" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#061a33"/><stop offset="1" stop-color="#0b2d5b"/></linearGradient><radialGradient id="g"><stop stop-color="#00b4ff" stop-opacity=".42"/><stop offset="1" stop-color="#00b4ff" stop-opacity="0"/></radialGradient></defs><rect width="1400" height="600" fill="url(#b)"/><circle cx="1080" cy="160" r="360" fill="url(#g)"/><path d="${patterns[variant] ?? patterns.signals}" fill="none" stroke="#00b4ff" stroke-width="12" stroke-linecap="round" stroke-linejoin="round" opacity=".82"/><circle cx="1120" cy="155" r="24" fill="#a3e635"/><circle cx="700" cy="300" r="7" fill="#fff" opacity=".8"/></svg>`;
}

export function renderReviewPage(review, token) {
  const cs = review.translations.cs;
  const en = review.translations.en;
  const available = review.review_status === "pending" && review.status === "draft" && new Date(review.expires_at) > new Date();
  const sources = review.sources.map((source) => `<li><a href="${escapeHtml(source.url)}" rel="noopener noreferrer">${escapeHtml(source.title)}</a><span>${escapeHtml(source.sourceName)}</span></li>`).join("");
  const sections = (translation) => translation.sections.map((section) => `<section><h3>${escapeHtml(section.heading)}</h3>${section.paragraphs.map((paragraph) => `<p>${escapeHtml(paragraph)}</p>`).join("")}</section>`).join("");
  const actions = available ? `<div class="review-actions"><form method="post" action="/blog/review/${encodeURIComponent(token)}/action"><input type="hidden" name="action" value="publish"><label><input type="checkbox" name="confirm" value="publish" required> Zkontroloval jsem obsah i zdroje a potvrzuji publikaci.</label><button type="submit">Publikovat článek</button></form><form method="post" action="/blog/review/${encodeURIComponent(token)}/action"><input type="hidden" name="action" value="reject"><label><input type="checkbox" name="confirm" value="reject" required> Potvrzuji zamítnutí tohoto návrhu.</label><button class="danger" type="submit">Zamítnout návrh</button></form></div>` : `<p class="review-state">Tento odkaz již není aktivní nebo byl návrh zpracován.</p>`;
  return `<!doctype html><html lang="cs"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="referrer" content="no-referrer"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/blog-assets/blog.css"><title>Redakční kontrola — VCode</title></head><body class="review-body"><main class="review-shell"><header><strong>VCode / redakční kontrola</strong><span>Návrh není veřejný</span></header><h1>${escapeHtml(cs.title)}</h1><p class="article-dek">${escapeHtml(cs.dek)}</p><dl class="review-meta"><div><dt>Model</dt><dd>${escapeHtml(review.model)}</dd></div><div><dt>Zdroje</dt><dd>${review.sources.length}</dd></div><div><dt>Odhad nákladů</dt><dd>$${Number(review.estimated_cost_usd).toFixed(4)}</dd></div><div><dt>Platnost</dt><dd>${formatDate(review.expires_at, "cs")}</dd></div></dl><article class="review-copy"><h2>Česká verze</h2>${sections(cs)}<h2>English version</h2><h3>${escapeHtml(en.title)}</h3><p>${escapeHtml(en.dek)}</p>${sections(en)}</article><section class="review-sources"><h2>Původní zdroje</h2><ul>${sources}</ul></section>${actions}</main></body></html>`;
}

export function renderReviewResult(status) {
  const published = status === "published";
  return `<!doctype html><html lang="cs"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/blog-assets/blog.css"><title>Redakční kontrola — VCode</title></head><body class="review-body"><main class="review-shell result"><span class="result-icon">${published ? "✓" : "×"}</span><h1>${published ? "Článek byl publikován" : "Návrh byl zamítnut"}</h1><p>${published ? "Článek je nyní dostupný na blogu VCode." : "Návrh zůstane v auditní historii a nebude zveřejněn."}</p><a class="result-link" href="/blog/">Přejít na blog</a></main></body></html>`;
}
