const $=id=>document.getElementById(id);
const number=new Intl.NumberFormat('cs-CZ');
const value=v=>Number(v?.value??v??0);
const showStatus=text=>$('status').textContent=text;
async function request(path,options={}){const r=await fetch('/prehled/api/'+path,{...options,headers:{'Content-Type':'application/json'},credentials:'same-origin'});const body=await r.json();if(!r.ok)throw Object.assign(new Error(body.error??'Přehled se nepodařilo načíst.'),{status:r.status});return body;}
function metric(label,count,previous){const el=document.createElement('div');el.className='metric';const strong=document.createElement('strong');strong.textContent=number.format(count);el.append(strong,document.createTextNode(label));if(previous!==undefined){const trend=document.createElement('small');trend.style.display='block';trend.textContent=previous>0?`${Math.round((count-previous)/previous*100)} % oproti předchozímu období`: 'Předchozí období bez údajů';el.append(trend);}return el;}
function list(title,rows){const section=document.createElement('div'),heading=document.createElement('h3');heading.textContent=title;section.append(heading);const ul=document.createElement('ul');for(const row of rows??[]){const li=document.createElement('li');const labels={'app-store-click':'Kliknutí do App Storu','contact-click':'Kliknutí na kontakt'};li.textContent=`${labels[row.x]??row.x??'Přímé / neurčené'} — ${number.format(Number(row.y??0))}`;ul.append(li);}if(!ul.children.length){const li=document.createElement('li');li.textContent='Zatím bez údajů.';ul.append(li);}section.append(ul);return section;}
async function load(){try{const data=await request('summary?days='+$('period').value);$('login').hidden=true;$('dashboard').hidden=false;$('collection').textContent=data.collectionEnabled?'Měření je aktivní.':'Měření čeká na schválení informace o soukromí. Zobrazené nuly neznamenají nulovou návštěvnost.';const totals={pageviews:0,visitors:0,clicks:0};$('sites').replaceChildren();for(const site of data.sites){totals.pageviews+=value(site.stats.pageviews);totals.visitors+=value(site.stats.visitors);totals.clicks+=(site.events??[]).filter(e=>e.x==='app-store-click').reduce((n,e)=>n+Number(e.y??0),0);const card=document.createElement('article');card.className='site';const heading=document.createElement('h2');heading.textContent=site.name;const domain=document.createElement('p');domain.textContent=site.domain;const figures=document.createElement('div');figures.className='totals';figures.append(metric('Zobrazení stránek',value(site.stats.pageviews),value(site.stats.comparison?.pageviews)),metric('Odhad návštěvníků',value(site.stats.visitors)),metric('Návštěvy',value(site.stats.visits)));const cols=document.createElement('div');cols.className='columns';cols.append(list('Nejnavštěvovanější stránky',(site.pages??[]).slice(0,10)),list('Zdroje příchodů',site.referrers),list('Zájem a kliknutí',site.events));const applications=new Map();for(const row of site.pages??[]){const match=/^\/(?:en\/)?(?:aplikace|apps|app-store|podpora|support|navody\/aplikace|guides\/apps)\/([a-z0-9-]+)\//.exec(row.x??'');if(match)applications.set(match[1],(applications.get(match[1])??0)+Number(row.y??0));}cols.append(list('Zobrazení stránek aplikací',[...applications].sort((a,b)=>b[1]-a[1]).map(([x,y])=>({x,y}))));card.append(heading,domain,figures,cols);$('sites').append(card);}$('totals').replaceChildren(metric('Zobrazení všech webů',totals.pageviews),metric('Součet odhadů návštěvníků',totals.visitors),metric('Kliknutí do App Storu',totals.clicks));showStatus(data.sites.length?'':'Zatím není připojený žádný web.');}catch(e){if(e.status===401){$('login').hidden=false;$('dashboard').hidden=true;}else showStatus(e.message);}}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{showStatus('Přihlašuji…');const data=Object.fromEntries(new FormData(e.target));await request('login',{method:'POST',body:JSON.stringify(data)});e.target.reset();showStatus('');await load();}catch(e){showStatus(e.message);}finally{button.disabled=false;}});
$('logout').addEventListener('click',async()=>{try{await request('logout',{method:'POST',body:'{}'});$('sites').replaceChildren();$('totals').replaceChildren();$('dashboard').hidden=true;$('login').hidden=false;showStatus('Odhlášeno.');}catch(e){showStatus(e.message);}});
$('refresh').addEventListener('click',load);$('period').addEventListener('change',load);load();
